//ERRORS
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

//PHONES
export const REQUEST_GET_ALL_PHONES = 'REQUEST_GET_ALL_PHONES';
export const RESPONSE_GET_ALL_PHONES_SUCCESS = 'RESPONSE_GET_ALL_PHONES_SUCCESS';
export const RESPONSE_GET_ALL_PHONES_ERROR = 'RESPONSE_GET_ALL_PHONES_ERROR';

export const REQUEST_GET_PHONE_BY_ID = 'REQUEST_GET_PHONE_BY_ID';
export const RESPONSE_GET_PHONE_BY_ID_SUCCESS = 'RESPONSE_GET_PHONE_BY_ID_SUCCESS';
export const RESPONSE_GET_PHONE_BY_ID_ERROR = 'RESPONSE_GET_PHONE_BY_ID_ERROR';